export enum ButtonName{
   JoinParty = "joinParty",
   DeclineParty = "declineParty",
   BattleAgain = "battleAgain",
   DeclineBattleAgain = "declineBattleAgain",
   QuestsMenu = "questsMenu",
   Adventure = "Adventure",
   ReturnToMenu = "ReturnToMenu",
   JobsMenu = "JobsMenu",
   SetJob = "SetJob",
   SetSubjob = "SetSubjob",
   SkillList = "SkillList",
   EquipMenu = "EquipMenu",
   SetPassives = "SetPassives",
   ShowBattleStatus = "ShowBattleStatus",
   ShowTurnDisplay = "ShowTurnDisplay",
   Forward = "Forward",
   Backward = "Backward",
   Left = "Left",
   Right = "Right",
   SlimeExtermination="SlimeExtermination"
}